### PR TITLE
Add UI config flow, remove time zone features & legacy tracker support

### LINKED ISSUE #55: Deprecated constants which will be removed in HA Core 2025.1
Hi!

HA logs have the following mention that some of the constants used will be deprecated in a year. Thanks already beforehand if you have the time to fix this in the near future @pnbruckner !

```
Logger: homeassistant.components.device_tracker
Source: helpers/deprecation.py:205
Integration: Device tracker ([documentation](https://www.home-assistant.io/integrations/device_tracker), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+device_tracker%22))
First occurred: 17:48:27 (8 occurrences)
Last logged: 17:48:27

SOURCE_TYPE_BLUETOOTH was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.BLUETOOTH instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
SOURCE_TYPE_BLUETOOTH_LE was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.BLUETOOTH_LE instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
SOURCE_TYPE_GPS was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.GPS instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
SOURCE_TYPE_ROUTER was used from composite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SourceType.ROUTER instead, please create a bug report at https://github.com/pnbruckner/ha-composite-tracker/issues
```

### PR DESCRIPTION
**Pull request by pnbruckner**
- [x] Integrate code from CompositeScanner class into CompositeDeviceTracker class.
- [x] Add reload service.
- [x] Add UI-based config flow.
- [x] Add support for sensors with lat/lon attributes.
- [x] Add translations.
~~- [ ] Add device info.~~
- [x] Remove time zone related features.
- [x] Remove legacy tracker support.
- [x] Remove imported configs no longer in YAML.
- [x] Handle frozen EntityDescription.
- [x] Update docs.

Closes #55.

### CODE REVIEW

**Comment by bcutter** [comment]
I'm urgently looking for this feature. Thanks a loooooooot for adding it!

I want to start using this integration, but using old .yaml is really not an option (anymore, we have 2024 - UI is king 👑! 😄 ).

When can we expect this UI config flow to ship with a release?

**Comment by pnbruckner** [comment]
@bcutter I was planning on releasing this as 3.0.0 very soon.

Regarding HA versions, yes, it does currently require at least 2023.7. That is already over a half year old. With all the changes that happen in the core system, and at such a fast rate, it gets really hard to support versions much older than that.

**Comment by bcutter** [comment]
Yeah I see. 👍 for releasing the stable 3.0 soon.
Indeed it gets. Sometimes developers are not paying specific attention to the `hacs.json` and simply enter the version used by their own like "this is the HA version I tested it with, so now this is required" which is why I - currently a bit behind with HA updates... - ask if there's an actual technical dependency.

But to be honest... this integration motivates me A LOT to update my HA asap (because as mentioned: UI > YAML) 😃

**Comment by pnbruckner** [comment]
> Sometimes developers are not paying specific attention to the hacs.json and simply enter the version used by their own like "this is the HA version I tested it with, so now this is required" which is why I - currently a bit behind with HA updates... - ask if there's an actual technical dependency.

I do _try_ to test with older versions to verify what the cutoff really is. Although I have been known to miss stuff if I try to do things too fast! 🤣 

I started writing some of the integrations quite long ago, and often have to add code to deal with new changes while trying to maintain backwards compatibility. Normally I comment the code where this happens as to what version required the changes. At some point I go back and rip out support for really old stuff, otherwise it gets a bit ridiculous.

In this case, I'm pretty sure it was 2023.7. I don't recall the details off the top of my head, but I'm pretty sure there was a significant change in that release such that supporting older versions became difficult, so many of my custom integrations use this version as the cutoff.

**Pull request merged**
